on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Make 'mvnw' executable
        run: chmod +x mvnw

      - name: Build Spring Boot Application
        run: |
          ./mvnw clean package

      - name: Build Docker image for Spring Boot
        run: docker build -t your-spring-app-image:1.0 -f Dockerfile .

      - name: Build Docker image for MySQL
        run: docker build -t mysql-database-image:1.0 -f Dockerfile-mysql .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push your-dockerhub-username/your-spring-app-image:1.0
          docker push your-dockerhub-username/mysql-database-image:1.0